---
title: "Data Exploration"
author: "Melissa Bischoff"
date: "10/11/2021"
output: html_document
---
```{r}
library(ggplot2)
library(dplyr)
cleanCols <- function(x){
  lower_names = tolower(names(x))
  sub_periods = gsub("\\.", "_", lower_names)
  sub_spaces = gsub(" ","_",sub_periods)
  clean_df_cols = gsub("__","_",sub_spaces)
  return(clean_df_cols)
}
```
```{r, fig.height = 4, fig.width = 6}
dhs_data_dashboard = read.csv('../data/department_of_homeless_services/DHS_Data_Dashboard.csv')
dhs_daily_report = read.csv('../data/department_of_homeless_services/DHS_Daily_Report.csv')
buildings = read.csv('../data/department_of_homeless_services/Buildings_by_Borough_and_Community_District.csv')
individual_census = read.csv('../data/department_of_homeless_services/Individual_Census_by_Borough__Community_District__and_Facility_Type.csv')
free_covid_meals = read.csv('../data/department_of_homeless_services/COVID-19_Free_Meals_Locations.csv')
doh_offices = read.csv('../data/department_of_homeless_services/Directory_Of_Homebase_Locations.csv')

names(dhs_data_dashboard) = cleanCols(dhs_data_dashboard)
names(dhs_daily_report) = cleanCols(dhs_daily_report)
names(buildings) = cleanCols(buildings)
names(individual_census) = cleanCols(individual_census)
names(free_covid_meals) = cleanCols(free_covid_meals)
names(doh_offices) = cleanCols(doh_offices)

dhs_data_dashboard = mutate(dhs_data_dashboard, id = row_number())
dhs_data_dashboard$date = as.Date(dhs_data_dashboard$report_date,
                                         format = "%m/%d/%Y")
dhs_data_dashboard$newdate = format(dhs_data_dashboard$date, "%Y-%m-%d")

pre_covid_data = dhs_data_dashboard[0:57,c('id','sa_avg_daily_census_individual_in_shelter__total','newdate')]
fit = lm(sa_avg_daily_census_individual_in_shelter__total ~ poly(id, degree=3),
         data = pre_covid_data)

data = data.frame(id = seq(1,57,1))
data$fitted = fit$fitted.values
  
new_data = data.frame(id = seq(58,72,1))
new_data$fitted = predict(fit, newdata = new_data)

full_data = rbind(data,new_data)
full_data$sa_avg_daily_census_individual_in_shelter__total = dhs_data_dashboard$sa_avg_daily_census_individual_in_shelter__total
full_data$newdate = dhs_data_dashboard$newdate
xlabels = full_data$newdate
xlabels[seq(2, length(xlabels), 2)] <- "   "


ggplot(full_data,
       aes(x = newdate, 
           y = sa_avg_daily_census_individual_in_shelter__total,
           group = 1)) +
  geom_line(aes(
    x=newdate,
    y=sa_avg_daily_census_individual_in_shelter__total,
    color = "actual values")) +
  geom_vline(aes(
    xintercept = dhs_data_dashboard$id[57],
    color = "covid start"),
    size=.7,
    linetype="dotted") +
  theme(axis.text.x = element_text(angle = 90)) +
  geom_line(aes(
    y = fitted,
    color = "fitted values"),
    size = .7) +
  scale_y_continuous(name = "Individuals in Shelter") +
  scale_x_discrete(
    name = "Month",
    labels = xlabels
    ) +
  ggtitle("Monthly Indivduals in Homeless Shelters") +
  scale_colour_manual(
    "", 
    breaks = c("actual values", "covid start", "fitted values"),
    values = c("darkblue", "red", "lightblue")
    )
```




